### TESTE REGISTRO

POST http://localhost:3000/registro/cliente
content-Type: application/json


		{
			"nome": "geraldo",
            "valor": 14123120,
            "status": "ALUGADO",
            "data": "2020-07-20"            
		}
	
###

GET http://localhost:3000/listar/aluguel


###

GET http://localhost:3000/listar/aluguel/60944b0125a659379c51bcc2

###

PUT http://localhost:3000/vender/editar/60946faa21a0f237c8b324e3

"cliente": [
{
    "nome": "Vagner",
    "cpf": "1125dasdasd4980",
    "Email": "Diogo@qweqwe",
    "Renda": 400,
    "FormaGarantia": "TEM"
  
}
]
